blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://community.home-assistant.io/t/composite-device-tracker-platform/67345
    about: Please ask and answer questions here.
